language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - PINS="protocol-9p:. protocol-9p-tool:. protocol-9p-unix:."
  matrix:
  - PACKAGE="protocol-9p" DISTRO="alpine" OCAML_VERSION="4.07"
  - PACKAGE="protocol-9p-unix" DISTRO="alpine" OCAML_VERSION="4.06"
  - PACKAGE="protocol-9p-tool" DISTRO="alpine" OCAML_VERSION="4.03"
