language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  matrix:
  - PACKAGE="bigstringaf" DISTRO="ubuntu-16.04" OCAML_VERSION="4.03"
  - PACKAGE="bigstringaf" DISTRO="ubuntu-16.04" OCAML_VERSION="4.04"
  - PACKAGE="bigstringaf" DISTRO="ubuntu-16.04" OCAML_VERSION="4.05" DEPOPTS="mirage-xen-posix"
  - PACKAGE="bigstringaf" DISTRO="ubuntu-16.04" OCAML_VERSION="4.06" DEPOPTS="ocaml-freestanding"
  - PACKAGE="bigstringaf" DISTRO="ubuntu-16.04" OCAML_VERSION="4.06" DEPOPTS="ocaml-freestanding"
  - PACKAGE="bigstringaf" DISTRO="ubuntu-16.04" OCAML_VERSION="4.07" DEPOPTS="ocaml-freestanding"
