language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
 global:
   - PINS="shared-memory-ring:. shared-memory-ring-lwt:."
 matrix:
   - DISTRO=alpine OCAML_VERSION=4.04 PACKAGE="shared-memory-ring"
   - DISTRO=alpine OCAML_VERSION=4.05 PACKAGE="shared-memory-ring-lwt"
   - DISTRO=alpine OCAML_VERSION=4.06 PACKAGE="shared-memory-ring"
   - DISTRO=alpine OCAML_VERSION=4.07 PACKAGE="shared-memory-ring-lwt"
