language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
dist: trusty
env:
  global:
  - PINS="mirage-console:. mirage-console-xen:. mirage-console-unix:. mirage-console-xen-backend:."
  matrix:
  - OCAML_VERSION=4.07 PACKAGE="mirage-console"
  - OCAML_VERSION=4.07 PACKAGE="mirage-console-lwt"
  - OCAML_VERSION=4.06 PACKAGE="mirage-console-unix"
  - OCAML_VERSION=4.05 PACKAGE="mirage-console-xen"
  - OCAML_VERSION=4.05 PACKAGE="mirage-console-lwt"
  - OCAML_VERSION=4.05 PACKAGE="mirage-console-unix"
  - OCAML_VERSION=4.04 PACKAGE="mirage-console-xen-proto"
  - OCAML_VERSION=4.04 PACKAGE="mirage-console-xen-backend"
  - OCAML_VERSION=4.04 PACKAGE="mirage-console-xen"
