language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
 global:
   - PACKAGE="ipaddr"
   - REVDEPS="true"
 matrix:
   - DISTRO=debian-testing OCAML_VERSION=4.03
   - DISTRO=debian-stable OCAML_VERSION=4.04
   - DISTRO=ubuntu OCAML_VERSION=4.05
   - DISTRO=alpine OCAML_VERSION=4.06
   - DISTRO=fedora OCAML_VERSION=4.07
