language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - PACKAGE="parse-argv"
  matrix:
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.03.0"
  - DISTRO="alpine" OCAML_VERSION="4.04.2"
  - DISTRO="debian-stable" OCAML_VERSION="4.05.0"
